product:
  name: product-service
  retry:
    count: 3
spring:
  cloud:
    function:
      defination: getAllProduct
      ineligible-definitions: getAllProduct1
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
management:
  endpoints:
    web:
      exposure:
        include: functions