server:
  port: 9200
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product_api
          uri: http://localhost:9300
          predicates:
            - Path=/functionRouter/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
