server:
  port: 9200
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: rewritepath_product_route
          uri: http://localhost:9300
          predicates:
            - Path=/product/**
          filters:
            - RewritePath=/product/*, /functionRouter
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
