server:
  port: 9100
encypt:
  key: sdshvur3hy843rehvurebfugh38re
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  security:
    user:
      name: root
      password: root
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/codesnaper/sample-microservice
##          The configuration server?s validation of the Git server?s SSL certificate can be disabled
          skipSslValidation: true
          timeout: 4
#          It tell to look on git search url in to pick property too
          search-paths:
            - config/merchant*
            - config/order*
            - config/product*
            - config/authClient*
            - config/discoveryserver*