spring:
  application:
    name: discover-server
  ssl:
    bundle:
      jks:
        server:
          key:
            alias: PRIVATE_KEY
          keystore:
            location: classpath:JKS/discovery-server/serverkey.p12
            password: ${KEY_STORE_PASSWORD}
            type: "PKCS12"

server:
  ssl:
    enabled: true
    bundle: server
    protocol: TLS
    enabled-protocols: TLSv1.2
  port: 9448
eureka:
  instance:
    hostname: discovery-server
  client:
    register-with-eureka: false
    fetch-registry: false