server:
  port: 9300
logging:
  level:
    root: DEBUG
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/sample-microservice
          jwk-set-uri: http://localhost:8080/realms/sample-microservice/protocol/openid-connect/certs
  application:
    name: product-service
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:9100
    config:
      label: main
      name: order
      username: root
      password: root