spring:
  application:
    name: auth-client
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:9100
    config:
      label: main
      name: authclient
      username: root
      password: root