spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${ISSUER_URI}
        registration:
          keycloak:
            redirect-uri: ${KEYCLOAK_REDIRECT_URI}
            client-id: ${KEYCLOAK_CLIENT_ID}
            provider: keycloak
            scope: openid
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            authorization-grant-type: authorization_code
logging:
  level:
    root: INFO
    org:
      springframework:
        security: TRACE
